### ISSUE TITLE
Per-Tenant Logging Validation

### ISSUE THREAD

**Issue by esune** [bcgov/traction#1013]
Validate whether per-tenant logging is working as expected and we can progress to standing-up the log monitoring stack to provide access to each tenant, or we need to update something (in which case, what?)

**Comment by amanji** [comment]
Testing this with a current setup:

1. Traction running in multitenant mode with 2 registered tenants Afternoons and Chests
2. Afternoons per-tenant logging level is set to `debug`:

![Image](https://github.com/bcgov/traction/assets/5605464/ab48db9c-6cfa-4a9a-9d69-cc5f60e10576)

## Observations:

The logs are outputting tenant-tenant specific logs using the Wallet ID` instead of the Tenant ID (which I think would be preferrable)

![Image](https://github.com/bcgov/traction/assets/5605464/f9e1c049-54ea-47c2-9479-ba03305b3513)

![Image](https://github.com/bcgov/traction/assets/5605464/90987d49-ae87-4540-b4f8-12b9ff689fb6)

I don't believe the log-level is being taken into account as I do not see any `DEBUG` statements in the console for either tenant.
