### ISSUE TITLE
I want to develop issuer functionality on a ledger without needing endorser

### ISSUE THREAD

**Issue by krobinsonca** [bcgov/traction#418]
I want to develop issuer functionality on a ledger without needing endorser

AC:
- can my development instance be configured to connect to a ledger without an endorser needed
- can Tenant UI issue a credential on a ledger without an endorser - would I get an error? How is error prevented/handled?

**Comment by esune** [comment]
@krobinsonca is there a specific use-case you were thinking of when you logged this?

Reading the ticket this use-case seems like something that would be addressed by using a standalone instance of ACA-Py, rather than a Traction tenant. This would provide full freedom, but require the extra set-up steps (registering your own DID on the ledger, meeting the Governance requisites to be considered an issuer, etc.)

**Comment by krobinsonca** [comment]
This was partly a developer experience item and partly a ticket for generic Traction to be used with a ledger that does not require an Endorser (non- BC Gov).

**Comment by esune** [comment]
Moving to `icebox` for future re-assessment.
