### ISSUE TITLE
Traction Documentation - Use Case videos

### ISSUE THREAD

**Issue by usingtechnology** [bcgov/traction#437]
Videos of Traction (old version) have been removed.
Decide whether they need to be replaced and log more issues to have them created and posted (where?) if needed.

**Comment by loneil** [comment]
As far as just Tenant UI I think it would be good to make a tenant/innkeeper reservation flow video. Just because I demo it enough that having that around would be good.
Probably the following too
- Invitations/connections
- Make tenant an issuer
- Schema creation and credential offer and revocation.

But then yeah, worth a discussion if making API-centric ones is worthwhile at this point.
