### ISSUE TITLE
What to do on the TenantUI messaging page

### ISSUE THREAD

**Issue by loneil** [bcgov/traction#522]
"Chat" style view has been added per-contact in the TenantUI but there's still the existing Messaging menu item that shows a table view of basic messaging records.

Need a UX decision on whether
1. This should be just kept as-is
2. This should be entirely removed
3. A different "all-users" view/design needs to be implemented.

**Comment by loneil** [comment]
@hiteshgh @esune would be nice to clear this ticket off quickly so I'd propose the following quick UX changes
- Keep the page as is
- Rename to "Message Audit" (or "Message History")
- Add some helper text at the top saying it's the list of all messages and you should go to Connections (with link) to "chat" with a specific connection
- Leave the + Message button there, add the connection dropdown to the form

**Comment by hiteshgh** [comment]
Tnx @loneil , we can ++ to nxt sprint ( lets discuss in planning meeting tomorrow ) , in the meantime i will add this to top of backlog so we remember it

**Comment by loneil** [comment]
Probably good quick one for Gavin that covers some more Traction functionality.

**Comment by swcurran** [comment]
Definitely don’t leave as is.  I can see maybe getting rid of it.  If we keep it, at an absolute minimum, add a dropdown to select a connection for sending a message (currently it is a prompt for a connection id). That should be trivial.  But I kind of think we just leave access to messaging in the connections screen.  It might be nice to have a way to see the unread message count by connections, or have the connections ordered by the most recently updated, including messages as updates.

**Comment by esune** [comment]
I think we would need to have a compelling use-case to keep the "extra" messaging page. The chat-style messaging we have seems adequate and provides a better user experience than the plain list of messages. We may want to align terminology with mobile wallets ("contacts" rather than "connections") and improve on the UI to support notifications for new unread messages as suggested by @swcurran , globally and on each contact row - this could be useful for hosted wallets.
![image](https://github.com/bcgov/traction/assets/2395873/23f08fc2-f0dd-4923-a630-c431a0a783e9)

The current messaging page seems redundant based on the information it is displaying (and how it is presenting it), maybe it could be repurposed and made more useful as a more "general" activity log, that would then include not only messages, but any type of interaction performed by the tenant (sent message, received credential offer, accepted credential offer, received presentation request, declined presentation request, etc.).

**Comment by loneil** [comment]
As part of some other minor connection fix I added the dropdown connection selector to the send message dialog.
The rest of this ticket about future need or enhancement for this mage remains though.
