### ISSUE TITLE
Upgrade to Postgres 14

### ISSUE THREAD

**Issue by esune** [bcgov/traction#539]
Traction is still using (a very old) using Postgres 10, and the latest versions of Askar drop support for older Postgres versions - causing the agent to be unable to start when in `askar` mode.

The Postgres dependency should be upgraded to Postgres 14:
- [ ] docker-compose.yaml
- [ ] Helm chart

**Comment by i5okie** [comment]
# Traction-DTS: PostgreSQL Upgrade Postmortem

@i5okie , @WadeBarnes , @usingtechnology 

Upgrade of the database instance for `traction-dts` uncovered issues resulting in prolonged downtime.

## What Happened

Since deploying Traction instance to the `dev` environment, the Helm chart files were refactored as was necessary to bring in needed imrpovements. Due to significant changes between already deployed `traction-dts` instance and the new Helm chart files on the development branch, the upgrade was unsuccessful. This caused a prolonged downtime as troubleshooting, and recovery attempt lasted several days. Upgrading the database ultimately succeeded using older Helm chart files.

### Chain of Events
- Created a new branch off `development`
- Updated Traction Helm chart files
- Scaled Traction deployments to 0
- Performed backup of three databases from the single instance of PostgreSQL 12
- Deleted `traction-dts` postgres stateful-set along with the PVC
- Performed Helm upgrade of `traction-dts` release with the updated values and template files
- Restored databases from backup
- Scaled `traction-dts` deployments to 1 replica each

    `traction-dts-acapy` pod went into CrashLoopBackOff due to several errors

- Updated Helm chart values. Replaced image tags `sha-4f98641` with `sha-f678ca9` and performed Helm upgrade again

    `traction-dts-acapy` was still showing errors

- Attempted to restore Helm release and database to previous version prior to modifications

    This did not seem to fix the errors.

- Updated Helm chart values and templates to match code from [`1b76b92a`](https://github.com/bcgov/traction/tree/1b76b92a62e5f673759bbcca3c364399c007e70d) commit;
- Modified Helm chart values and templates as necessary to upgrade the Bitnami PostgreSQL Helm chart dependency from 10.16.2 to 11.9.13
- Scaled `traction-dts` deployments to 0, deleted `traction-dts` statefulset along with its PVC
- Performed Helm upgrade of `traction-dts` release with the updated values and template files
- Restored databases from backup
- Scaled `traction-dts` deployments back, up to 1 replica each

    No errors were present. At this point `traction-dts` database upgrade and data restore have been validated and deemed successful.

## Root Cause
Along with significant changes to the Helm chart values and template files on development branch, two important values, `wallet-name`, and `wallet-key` were missing in the updated code. `wallet-name` and `wallet-key` used to be hard coded in the templates.

## Resolution
Using the older Helm chart values and files to perform the postgres upgrade and re-deployment prooved to be successful.

## Impact
Traction development instance, `traction-dts` was offline from April 17th to April 19th.
BC Wallet Showcase demo, and dev instance were both connected to `traction-dts` and thus were impacted by the downtime.

## Action Items
- Test Helm chart files, and latest built images from `development` branch with proper values in a separate deployment and copy of the data from `traction-dts` deployment
- Create a PR with updated Helm chart values/template files if successful

**Comment by esune** [comment]
Thank you for the detailed review @i5okie. I think the activities resulting from this will also affect #537 as it is about having proper chart versioning. Up to you how to split the work, in general we will want to get to a state where:
- Helm charts have been updated/refactored appropriately, as per your write-up
- Helm charts are easily maintainable in a release process (i.e.: released images are correctly referenced in the chart)
