### ISSUE TITLE
i18n is not loading Intermittently  

### ISSUE THREAD

**Issue by hiteshgh** [bcgov/traction#600]
i18n is not loading Intermittently  

Think it started happening after https://github.com/bcgov/traction/pull/568 / https://github.com/bcgov/traction/issues/465

**Comment by loneil** [comment]
Notice this on the front page occasionally now (always front page since that loads first), and then any Vue reactivity update _seems_ to fix it. So the string re-rendering or loading another page etc.

![image](https://github.com/bcgov/traction/assets/17445138/69d6a0cc-b098-41bc-ae3c-8db0015461a7)


Hadn't had this happen before, only things I can think of off the top of my head:

-  Using the **global** `{{ $t('string.goes.here') }}` instead of the composable that it used to use ?
```
import { useI18n } from 'vue-i18n';
const { t } = useI18n();
```
- Just that the language jsons are bigger now and take longer to load causing a race condition?
