### ISSUE TITLE
Update AC-Py image

### ISSUE THREAD

**Issue by esune** [bcgov/traction#640]
Update ACA-Py image to use latest non-indy release, see here: https://github.com/hyperledger/aries-cloudagent-python/pkgs/container/aries-cloudagent-python/83518866?tag=py3.9-0.8.1

While doing this, review the [Traction agent Dockerfile](https://github.com/bcgov/traction/blob/develop/plugins/docker/Dockerfile) and remove the dependency on `von-image` (if possible).

**Comment by WadeBarnes** [comment]
Not sure if this issue would impact Traction upgrading to `0.8.1`; https://github.com/hyperledger/aries-cloudagent-python/issues/2224

**Comment by swcurran** [comment]
@esune — when updating an existing deployment, you have to be worried about the upgrade process. Because I messed up with creating 1.0.0-rc1, and Traction used it, you are upgrading by content, but downgrading by number. Because of the upgrade logic we put in 0.8.1, I’m pretty sure it will work (see below), and even if it doesn’t it probably won’t matter unless an instance is used a multi-use invitation on an ongoing basis.

As @WadeBarnes notes — ACA-Py 2444 is probably the bigger issue, but it will either work or not. @usingtechnology came up with a fix for that yesterday, so if it is a problem — look at that.

Why the upgrade **should** work.  In 0.8.1, we added a “feature” that if there is no version number in storage, we would assume the agent is running 0.7.5. Prior to that, in ACA-Py, the version number in storage was only written when an upgrade was done.  So, if a Traction instance was not upgraded (which had to be explicit), the install of 0.8.1 will trigger a 0.7.5-to-0.81 upgrade, which is what you want.  All good…probably.  :-)

**Comment by esune** [comment]
Thanks for the heads up. I am not too concerned about upgrading the running instances: all the deployments we currently have will luckily be recycled pretty soon, so they can stay at the current version if necessary. The issue is - mostly - to upgrade the image in the repository so that a newer agent is used moving forward.

We can make this change just before we tear down and redeploy the instances we need to reduce the headaches with version compatibility 😉

**Comment by esune** [comment]
Completed as part of #599. Current deployments will be re-created from scratch if there are issues upgrading to the newer image version.
