### ISSUE TITLE
SPIKE - Expose configuration to Tenant UI

### ISSUE THREAD

**Issue by esune** [bcgov/traction#648]
Acceptance Criteria:
Settings such as ACA-Py version, ledger(s), installed plugins, tails server should be exposed by the Traction plugin so that the Tenant UI (or other client) could consume them.

**Comment by esune** [comment]
@loneil this would be another good candidate to tackle soon, as it would simplify deployments and make front/back ends consistent in behaviour.

**Comment by loneil** [comment]
Yeah I was just thinking I'd like to know exact ACA-Py release in the About page (rather than the config-defined hard-coded value in the JSON).
I was thinking the best way is actually to take the image being pulled into the helm chart/docker env and make an environment variable that config picks up on. So then the exact image tag is known to the Tenant UI.

But then there's all the other config values that would be good to be known from ACA-Py. So maybe both of those things here.

Could be tackled soon yes.

**Comment by esune** [comment]
I think with this spike we want to get to a list of:
- what does the tenant UI need to know exactly
- what does ACA-Py expose already
- what is missing, but is required

We can then come up with a strategy to consolidate.

**Comment by esune** [comment]
Making this high priority: as we move to support production usage of Traction, having less moving parts is going to be essential to maintain operational reliability.

**Comment by loneil** [comment]
@esune I should be good to start on this tomorrow if we want.
