### ISSUE TITLE
suggestion: QR Code generation URL for invitation

### ISSUE THREAD

**Issue by cvarjao** [bcgov/traction#678]
There are currently 2 main endpoints for generating invitations:
- `POST /connections/create-invitation`
- `POST /out-of-band/create-invitation`

both returns a `invitation_url` property. Would be possible to also return an `invitation_qrcore_url` with a link to an endpoint that returns the generate QRCode image (e.g.:png)?

**Comment by esune** [comment]
What would be the use-case for this? we found that if the QR Code needs to be displayed in a user interface it is easier to have it generate it and embed it as needed, rather than having to deal with generating and transferring image files. Also keep in mind that the proposed approach would make it impossible to add a URL shortener service - if needed.

**Comment by esune** [comment]
Closing as the QR Code generation seems more like a frontend capability.
