### ISSUE TITLE
Upgrade existing tests to account for the showWritableComponents flag

### ISSUE THREAD

**Issue by popkinj** [bcgov/traction#758]
There are settings within the Tenant UI that remove various elements, depending on levels of permission. Work on [#717](https://github.com/bcgov/traction/issues/new#workspaces/bcgov-ditp-products-team-63c987121278d5001ecb177b/board), has turned off tests that relate to components with write permissions to the Database or Ledger.

**Comment by loneil** [comment]
Might be some misunderstanding, tests don't relate to the helm values in the yamls at all, those are deployment side, whereas the unit tests run non-deployed code. The code will never know anything about values.

It's not about turning on or off tests IMO. A unit test should just exercise code based on inputs to check expected output. So simply what's needed is the test exercising the component to go "based on this value in the **config store** (so that's easily mockable without needing to know anything about actual config deployment values), should this button be visible, or not?"

See @jamshale comment here https://github.com/bcgov/traction/pull/743#issuecomment-1660789719
this concept is already done in another test.

**Comment by popkinj** [comment]
> Might be some misunderstanding, tests don't relate to the helm values in the yamls at all, those are deployment side, whereas the unit tests run non-deployed code. The frontend code will never know anything about helm chart values.
> 
> It's not about turning on or off tests IMO. A unit test should just exercise code based on inputs to check expected output. So simply what's needed is the test exercising the component to go "based on this value in the **config store** (so that's easily mockable/changeable-in-scope without needing to know anything about actual config deployment values), should this button be visible, or not?"
> 
> See @jamshale comment here [#743 (comment)](https://github.com/bcgov/traction/pull/743#issuecomment-1660789719) this concept is already done in another test.

Hmmm... 🤔 ... Think I get what you're saying @loneil .
So maybe change this ticket to something like... Upgrade existing tests to account for the  `showWritableComponents` flag??

**Comment by loneil** [comment]
"Upgrade existing tests to account for the showWritableComponents flag" is perfect 😄

**Comment by jamshale** [comment]
I can do this ticket. Could be reference for changing configs in the future.
