### ISSUE TITLE
Move "generic" plug-in code to the shared plug-in repository

### ISSUE THREAD

**Issue by esune** [bcgov/traction#857]
Traction includes a collection of plug-ins for ACA-Py, they are all in the [plugins](https://github.com/bcgov/traction/tree/main/plugins) folder. Some of these plug-ins are generic enough that could/should be moved to the general ACA-Py plug-ins repository: https://github.com/hyperledger/aries-acapy-plugins

Candidates for the move are:
- `basicmessage_storage`
- `connection_update`
- `multitenant_provider`

Acceptance Criteria:
- Plug-In code is moved to the new repository
- Traction build steps are updated to handle the change

**Comment by esune** [comment]
@usingtechnology I think I described the issue well enough, please chime in if there is anything to add.

**Comment by usingtechnology** [comment]
`basicmessage_storage` is the example i used (used the latest code).

Since we used that as an example for other contributors, I added in a (super simple) [pytest](https://github.com/hyperledger/aries-acapy-plugins/blob/main/basicmessage_storage/basicmessage_storage/v1_0/tests/test_models.py), added in an [integration](https://github.com/hyperledger/aries-acapy-plugins/blob/main/basicmessage_storage/integration/README.md) "test" (we should probably move to BDD as the example). The pytest in this case was mostly put in place to make sure the devcontainer would find and run them. We should probably write something useful here.

Added in devcontainer + launch.json to run acapy with the plugin. In order to get that all running, I had to update the pyproject.toml to include other dependencies needed for integration tests. These should NOT get added when installing the plugin in the wild, only included if specifically asked for (in the devcontainer for dev work and in the integration test image).

We also want to encourage better / easier to digest information about the plugin - why it exists, what it does, how a consumer would leverage it, what it requires (ie multitenancy, other plugins). So the [README.md](https://github.com/hyperledger/aries-acapy-plugins/blob/main/basicmessage_storage/README.md) should be fleshed out.  There is also a [sample plugin config](https://github.com/hyperledger/aries-acapy-plugins/blob/main/basicmessage_storage/plugin-config.yml.sample) file that should be populated as documentation about how to configure it and all the various options.

**Comment by swcurran** [comment]
It would be nice to get the list of plugins listed in https://aca-py.org

For that we would need:

- A plugins repo README
- A how to contribute MD file
- A README per plugin that defines purpose, how to include in a deployment, how to use

Anything more needed?

**Comment by esune** [comment]
I feel like the "how to add to a deployment" might need to be a global readme (if not the main one) in the plugins repo, rather than per-plugin. This way we would incentivize standardization.

**Comment by jamshale** [comment]
All the plugins are now in the plugin repo `basic_messages`, `connection_update` and `multitenant_provider` and unit tested and integration tested.

When the plugin repo has versioning and it's first release then traction can remove the code and install the plugins remotely. I will create a ticket for it when the plugin repo is ready.

**Comment by jamshale** [comment]
There are open and closed tickets in `aries-acapy-plugins` repo related to this ticket.

**Comment by swcurran** [comment]
Great work!  We need to get a LinkedIn/Blog post to the broader Aries community about the ACA-Py plugins repo.  @krobinsonca — perhaps you could get the delivery team to help with that?  We should also think about adding a simple GH Pages webpage to publize the repo. mkdocs makes that pretty easy.

@dbluhm FYI about getting word out about the
