### ISSUE TITLE
Update email address for approved tenant

### ISSUE THREAD

**Issue by esune** [bcgov/traction#900]
Add functionality to update the recorded contact email for approved/registered tenants: this is useful if the contact person responsible for the tenant changes, and communications need to be routed to someone else.

**Comment by loneil** [comment]
We don't actually have any link between the Tenant and the Reservation that created it (could consider adding a tenant field that contains reservation ID maybe), but would be easy enough to have an update endpoint to the Reservation (then you can just look through reservations for the matching Tenant name to get the email).

**Comment by esune** [comment]
Yeah, I think this would be self-managed by the tenant and would give them a way to always have up-to-date contact information for communications, etc.

**Comment by loneil** [comment]
@esune do we want to maybe just have an add-on set of "TenantContact" records for Tenant here?
one-to-many Tenant > TenantContact. CRUD endpoints for that, Tenant can add/edit/delete.

So on reservation creation it could create the first one of those with the email address of the reserver (and only email address, as we can't rely on other fields being there since the reservation form can vary). Then the Tenant can manage them themselves from their profile page?

**Comment by esune** [comment]
It's more data we would be storing, so I am not sure. I would expect a main contact to always be kept up-to-date and be the one who would relay information back to each team, as needed so I think I'd start with that and see if we need to do more.

**Comment by loneil** [comment]
Ok then we would be at

1. allow the tenant to update the Reservation record after the tenant was already created (probably don't want because we might want history of the reservation preserved)
2. Add a contact field to the tenant record (or the fuller one-to-many example above)
